const mergeConfigs = {
  manga: {
    key: 'manga',
    label: 'Lecture (Manga)',
    table: 'manga_series',
    titleField: 'titre',
    coverField: 'couverture_url',
    reportType: 'manga_series-merge',
    previewFields: [
      { key: 'titre', label: 'Titre', type: 'text' },
      { key: 'titre_romaji', label: 'Titre romaji', type: 'text' },
      { key: 'titre_natif', label: 'Titre natif', type: 'text' },
      { key: 'titre_anglais', label: 'Titre anglais', type: 'text' },
      { key: 'titres_alternatifs', label: 'Titres alternatifs', type: 'list' },
      { key: 'couverture_url', label: 'Couverture', type: 'image' },
      { key: 'description', label: 'Description', type: 'longText' },
      { key: 'mal_id', label: 'MAL ID', type: 'badge' },
      { key: 'source_url', label: 'URL source', type: 'link' },
      { key: 'source_id', label: 'ID source', type: 'text' },
      { key: 'genres', label: 'Genres', type: 'chips' },
      { key: 'themes', label: 'Thèmes', type: 'chips' },
      { key: 'demographie', label: 'Démographie', type: 'text' },
      { key: 'langue_originale', label: 'Langue originale', type: 'text' },
      { key: 'media_type', label: 'Type média', type: 'badge' },
      { key: 'type_volume', label: 'Type de volume', type: 'text' },
      { key: 'type_contenu', label: 'Type de contenu', type: 'text' },
      { key: 'nb_volumes', label: 'Nb volumes VO', type: 'number' },
      { key: 'nb_volumes_vf', label: 'Nb volumes VF', type: 'number' },
      { key: 'nb_chapitres', label: 'Nb chapitres VO', type: 'number' },
      { key: 'nb_chapitres_vf', label: 'Nb chapitres VF', type: 'number' },
      { key: 'statut_publication', label: 'Statut publication VO', type: 'text' },
      { key: 'statut_publication_vf', label: 'Statut publication VF', type: 'text' },
      { key: 'annee_publication', label: 'Année publication VO', type: 'number' },
      { key: 'annee_vf', label: 'Année VF', type: 'number' },
      { key: 'auteurs', label: 'Auteurs', type: 'chips' },
      { key: 'editeur', label: 'Éditeur VF', type: 'text' },
      { key: 'editeur_vo', label: 'Éditeur VO', type: 'text' },
      { key: 'serialization', label: 'Sérialisation', type: 'text' },
      { key: 'rating', label: 'Classification', type: 'badge' },
      { key: 'score_mal', label: 'Score MAL', type: 'number' },
      { key: 'rank_mal', label: 'Classement MAL', type: 'number' },
      { key: 'popularity_mal', label: 'Popularité MAL', type: 'number' },
      { key: 'background', label: 'Background', type: 'longText' },
      { key: 'relations', label: 'Relations (JSON)', type: 'json' }
    ]
  },
  anime: {
    key: 'anime',
    label: 'Anime',
    table: 'anime_series',
    titleField: 'titre',
    coverField: 'couverture_url',
    reportType: 'anime_series-merge',
    previewFields: [
      { key: 'titre', label: 'Titre', type: 'text' },
      { key: 'titre_romaji', label: 'Titre romaji', type: 'text' },
      { key: 'titre_natif', label: 'Titre natif', type: 'text' },
      { key: 'titre_anglais', label: 'Titre anglais', type: 'text' },
      { key: 'titres_alternatifs', label: 'Titres alternatifs', type: 'list' },
      { key: 'couverture_url', label: 'Couverture', type: 'image' },
      { key: 'description', label: 'Synopsis', type: 'longText' },
      { key: 'mal_id', label: 'MAL ID', type: 'badge' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'source', label: 'Source', type: 'text' },
      { key: 'statut_diffusion', label: 'Statut diffusion', type: 'text' },
      { key: 'en_cours_diffusion', label: 'En cours de diffusion', type: 'boolean' },
      { key: 'date_debut', label: 'Date de début', type: 'date' },
      { key: 'date_fin', label: 'Date de fin', type: 'date' },
      { key: 'saison_diffusion', label: 'Saison de diffusion', type: 'text' },
      { key: 'annee', label: 'Année', type: 'number' },
      { key: 'genres', label: 'Genres', type: 'chips' },
      { key: 'themes', label: 'Thèmes', type: 'chips' },
      { key: 'demographics', label: 'Démographie', type: 'text' },
      { key: 'studios', label: 'Studios', type: 'chips' },
      { key: 'producteurs', label: 'Producteurs', type: 'chips' },
      { key: 'diffuseurs', label: 'Diffuseurs', type: 'chips' },
      { key: 'editeur', label: 'Éditeur', type: 'text' },
      { key: 'site_web', label: 'Site officiel', type: 'link' },
      { key: 'rating', label: 'Classification', type: 'badge' },
      { key: 'score', label: 'Score', type: 'number' },
      { key: 'rank_mal', label: 'Classement MAL', type: 'number' },
      { key: 'popularity_mal', label: 'Popularité MAL', type: 'number' },
      { key: 'liens_streaming', label: 'Liens streaming', type: 'json' },
      { key: 'liens_externes', label: 'Liens externes', type: 'json' },
      { key: 'manga_source_mal_id', label: 'Source manga MAL ID', type: 'badge' },
      { key: 'light_novel_source_mal_id', label: 'Source LN MAL ID', type: 'badge' },
      { key: 'relations', label: 'Relations', type: 'json' }
    ]
  },
  movie: {
    key: 'movie',
    label: 'Film',
    table: 'movies',
    titleField: 'titre',
    coverField: 'poster_path',
    reportType: 'movies-merge',
    previewFields: [
      { key: 'titre', label: 'Titre', type: 'text' },
      { key: 'titre_original', label: 'Titre original', type: 'text' },
      { key: 'synopsis', label: 'Synopsis', type: 'longText' },
      { key: 'poster_path', label: 'Affiche', type: 'image' },
      { key: 'backdrop_path', label: 'Backdrop', type: 'image' },
      { key: 'date_sortie', label: 'Date de sortie', type: 'date' },
      { key: 'duree', label: 'Durée (min)', type: 'number' },
      { key: 'genres', label: 'Genres', type: 'chips' },
      { key: 'mots_cles', label: 'Mots-clés', type: 'chips' },
      { key: 'langues_parlees', label: 'Langues parlées', type: 'chips' },
      { key: 'compagnies', label: 'Compagnies', type: 'chips' },
      { key: 'pays_production', label: 'Pays de production', type: 'chips' },
      { key: 'site_officiel', label: 'Site officiel', type: 'link' },
      { key: 'note_moyenne', label: 'Note moyenne', type: 'number' },
      { key: 'nb_votes', label: 'Nombre de votes', type: 'number' },
      { key: 'popularite', label: 'Popularité', type: 'number' },
      { key: 'adulte', label: 'Contenu adulte', type: 'boolean' },
      { key: 'budget', label: 'Budget', type: 'number' },
      { key: 'revenus', label: 'Revenus', type: 'number' },
      { key: 'rating', label: 'Classification', type: 'badge' },
      { key: 'ids_externes', label: 'IDs externes', type: 'json' }
    ]
  },
  tv: {
    key: 'tv',
    label: 'Série TV',
    table: 'tv_shows',
    titleField: 'titre',
    coverField: 'poster_path',
    reportType: 'tv_shows-merge',
    previewFields: [
      { key: 'titre', label: 'Titre', type: 'text' },
      { key: 'titre_original', label: 'Titre original', type: 'text' },
      { key: 'synopsis', label: 'Synopsis', type: 'longText' },
      { key: 'poster_path', label: 'Affiche', type: 'image' },
      { key: 'backdrop_path', label: 'Backdrop', type: 'image' },
      { key: 'type', label: 'Type', type: 'badge' },
      { key: 'statut', label: 'Statut', type: 'text' },
      { key: 'nb_saisons', label: 'Nombre de saisons', type: 'number' },
      { key: 'nb_episodes', label: 'Nombre d\'épisodes', type: 'number' },
      { key: 'duree_episode', label: 'Durée d\'épisode', type: 'number' },
      { key: 'date_premiere', label: 'Première diffusion', type: 'date' },
      { key: 'date_derniere', label: 'Dernière diffusion', type: 'date' },
      { key: 'prochain_episode', label: 'Prochain épisode', type: 'text' },
      { key: 'dernier_episode', label: 'Dernier épisode', type: 'text' },
      { key: 'genres', label: 'Genres', type: 'chips' },
      { key: 'mots_cles', label: 'Mots-clés', type: 'chips' },
      { key: 'langues_parlees', label: 'Langues parlées', type: 'chips' },
      { key: 'compagnies', label: 'Compagnies', type: 'chips' },
      { key: 'pays_production', label: 'Pays de production', type: 'chips' },
      { key: 'reseaux', label: 'Réseaux', type: 'chips' },
      { key: 'plateformes', label: 'Plateformes', type: 'chips' },
      { key: 'note_moyenne', label: 'Note moyenne', type: 'number' },
      { key: 'nb_votes', label: 'Nombre de votes', type: 'number' },
      { key: 'popularite', label: 'Popularité', type: 'number' }
    ]
  },
  game: {
    key: 'game',
    label: 'Jeu adulte',
    table: 'adulte_game_games',
    titleField: 'titre',
    coverField: 'couverture_url',
    reportType: 'adulte_game-merge',
    previewFields: [
      { key: 'titre', label: 'Titre', type: 'text' },
      { key: 'game_version', label: 'Version du jeu', type: 'text' },
      { key: 'game_statut', label: 'Statut du jeu', type: 'text' },
      { key: 'game_engine', label: 'Moteur', type: 'text' },
      { key: 'game_developer', label: 'Développeur', type: 'text' },
      { key: 'game_site', label: 'Site', type: 'badge' },
      { key: 'couverture_url', label: 'Couverture', type: 'image' },
      { key: 'tags', label: 'Tags', type: 'chips' },
      { key: 'lien_f95', label: 'Lien F95', type: 'link' },
      { key: 'lien_lewdcorner', label: 'Lien Lewdcorner', type: 'link' },
      { key: 'statut_traduction', label: 'Statut traduction', type: 'text' },
      { key: 'type_traduction', label: 'Type traduction', type: 'text' },
      { key: 'traduction_fr_disponible', label: 'Traduction fr dispo', type: 'boolean' },
      { key: 'version_traduite', label: 'Version traduite', type: 'text' },
      { key: 'lien_traduction', label: 'Lien traduction', type: 'link' },
      { key: 'traducteur', label: 'Traducteur', type: 'text' },
      { key: 'derniere_sync_trad', label: 'Dernière sync trad', type: 'date' },
      { key: 'traductions_multiples', label: 'Traductions multiples', type: 'json' },
      { key: 'maj_disponible', label: 'MAJ disponible', type: 'boolean' },
      { key: 'user_modified_fields', label: 'Champs modifiés (JSON)', type: 'json' }
    ]
  }
};

module.exports = { mergeConfigs };
